# -*- coding: utf-8 -*-
#
# sphinx_essc_geo documentation build configuration file, created by
# sphinx-quickstart on Tue May 18 09:01:35 2010.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.append(os.path.abspath('.'))

# -- General configuration -----------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.doctest', 'sphinx.ext.intersphinx', 'sphinx.ext.todo', 'sphinx.ext.coverage', 'sphinx.ext.pngmath', 'sphinx.ext.ifconfig', 'sphinx.ext.viewcode']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'CLP-FFI-ESSC FOSS4G Workshop 2013'
copyright = u'2013, ESSC and FFI license under GNU Free Document License'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.1'
# The full version, including alpha/beta/rc tags.
release = '0.1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
today_fmt = '%B %d %Y %H:%M:%S'

# List of documents that shouldn't be included in the build.
#unused_docs = ['intro.rst', 'chapter1.rst']

# List of directories, relative to source directory, that shouldn't be searched
# for source files.
exclude_trees = ['_build']

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []


# TODO:check for duplicate entries
rst_epilog = """
.. |mActionAddBasicShape| image:: images/qgis_icons/mActionAddBasicShape.png
                          :width: 20 pt
.. |mActionAddImage| image:: images/qgis_icons/mActionAddImage.png
                     :width: 20 pt
.. |mActionAddLegend| image:: images/qgis_icons/mActionAddLegend.png
                      :width: 20 pt
.. |mActionAddMap| image:: images/qgis_icons/mActionAddMap.png
                   :width: 20 pt
.. |mActionAddOgrLayer| image:: images/qgis_icons/mActionAddOgrLayer.png
                        :width: 20 pt
.. |mActionAddRasterLayer| image:: images/qgis_icons/mActionAddRasterLayer.png
                           :width: 20 pt
.. |mActionAddWmsLayer| image:: images/qgis_icons/mActionAddWmsLayer.png
                        :width: 20 pt
.. |mActionAlignLeft| image:: images/qgis_icons/mActionAlignLeft.png
                      :width: 20 pt
.. |mActionCalculateField| image:: images/qgis_icons/mActionCalculateField.png
                           :width: 20 pt
.. |mActionAddFeatureLine| image:: images/qgis_icons/mActionAddFeatureLine.png
                        :width: 20 pt
.. |mActionAddFeaturePoint| image:: images/qgis_icons/mActionAddFeaturePoint.png
                         :width: 20 pt
.. |mActionAddFeaturePolygon| image:: images/qgis_icons/mActionAddFeaturePolygon.png
                           :width: 20 pt
.. |mActionCopySelected| image:: images/qgis_icons/mActionCopySelected.png
                         :width: 20 pt
.. |mActionDeleteAttribute| image:: images/qgis_icons/mActionDeleteAttribute.png
                            :width: 20 pt
.. |mActionDeleteSelected| image:: images/qgis_icons/mActionDeleteSelected.png
                           :width: 20 pt
.. |mActionDraw| image:: images/qgis_icons/mActionDraw.png
                 :width: 20 pt
.. |mActionEditCopy| image:: images/qgis_icons/mActionEditCopy.png
                     :width: 20 pt
.. |mActionEditCut| image:: images/qgis_icons/mActionEditCut.png
                    :width: 20 pt
.. |mActionEditPaste| image:: images/qgis_icons/mActionEditPaste.png
                      :width: 20 pt
.. |mActionFileNew| image:: images/qgis_icons/mActionFileNew.png
                    :width: 20 pt
.. |mActionFilePrint| image:: images/qgis_icons/mActionFilePrint.png
                      :width: 20 pt
.. |mActionFileSave| image:: images/qgis_icons/mActionFileSave.png
                     :width: 20 pt
.. |mActionGroupItems| image:: images/qgis_icons/mActionGroupItems.png
                       :width: 20 pt
.. |mActionIdentify| image:: images/qgis_icons/mActionIdentify.png
                     :width: 20 pt
.. |mActionInvertSelection| image:: images/qgis_icons/mActionInvertSelection.png
                            :width: 20 pt
.. |mActionLabel| image:: images/qgis_icons/mActionLabel.png
                  :width: 20 pt
.. |mActionMeasureArea| image:: images/qgis_icons/mActionMeasureArea.png
                        :width: 20 pt
.. |mActionMeasure| image:: images/qgis_icons/mActionMeasure.png
                    :width: 20 pt
.. |mActionMoveFeature| image:: images/qgis_icons/mActionMoveFeature.png
                        :width: 20 pt
.. |mActionNewAttribute| image:: images/qgis_icons/mActionNewAttribute.png
                         :width: 20 pt
.. |mActionNewComposer| image:: images/qgis_icons/mActionNewComposer.png
                        :width: 20 pt
.. |mActionNewVectorLayer| image:: images/qgis_icons/mActionNewVectorLayer.png
                           :width: 20 pt
.. |mActionNodeTool| image:: images/qgis_icons/mActionNodeTool.png
                     :width: 20 pt
.. |mActionOptions| image:: images/qgis_icons/mActionOptions.png
                    :width: 20 pt
.. |mActionPan| image:: images/qgis_icons/mActionPan.png
                :width: 20 pt
.. |mActionRaiseItems| image:: images/qgis_icons/mActionRaiseItems.png
                       :width: 20 pt
.. |mActionSaveAsPDF| image:: images/qgis_icons/mActionSaveAsPDF.png
                      :width: 20 pt
.. |mActionSaveMapAsImage| image:: images/qgis_icons/mActionSaveMapAsImage.png
                           :width: 20 pt
.. |mActionScaleBar| image:: images/qgis_icons/mActionScaleBar.png
                     :width: 20 pt
.. |mActionSelectPan| image:: images/qgis_icons/mActionSelectPan.png
                      :width: 20 pt
.. |mActionSelectedToTop| image:: images/qgis_icons/mActionSelectedToTop.png
                          :width: 20 pt
.. |mActionShowPluginManager| image:: images/qgis_icons/mActionShowPluginManager.png
                              :width: 20 pt
.. |mActionToggleEditing| image:: images/qgis_icons/mActionToggleEditing.png
                          :width: 20 pt
.. |mActionUngroupItems| image:: images/qgis_icons/mActionUngroupItems.png
                         :width: 20 pt
.. |mActionUnselectAttributes| image:: images/qgis_icons/mActionUnselectAttributes.png
                               :width: 20 pt
.. |mActionZoomFullExtent| image:: images/qgis_icons/mActionZoomFullExtent.png
                           :width: 20 pt
.. |mActionZoomIn| image:: images/qgis_icons/mActionZoomIn.png
                   :width: 20 pt
.. |mActionZoomLast| image:: images/qgis_icons/mActionZoomLast.png
                     :width: 20 pt
.. |mActionZoomOut| image:: images/qgis_icons/mActionZoomOut.png
                    :width: 20 pt
.. |mActionZoomToLayer| image:: images/qgis_icons/mActionZoomToLayer.png
                        :width: 20 pt
.. |mActionZoomToSelected| image:: images/qgis_icons/mActionZoomToSelected.png
                           :width: 20 pt
.. |plugin_installer| image:: images/qgis_icons/plugin_installer.png
                      :width: 20 pt
.. |adddelimitedtext| image:: images/qgis_icons/adddelimitedtext.png
                      :width: 20 pt
.. |mActionGPSTools| image:: images/qgis_icons/mActionGPSTools.png
                     :width: 20pt
.. |mActionAddBingLayer| image:: images/qgis_icons/mActionAddBingLayer.png
                         :width: 20pt
.. |mActionLabeling| image:: images/qgis_icons/mActionLabeling.png
                     :width: 20pt
.. |vector_grid| image:: images/qgis_icons/ftools/vector_grid.png
                 :width: 20pt
.. |unique| image:: images/qgis_icons/ftools/unique.png
            :width: 20pt
.. |union| image:: images/qgis_icons/ftools/union.png
           :width: 20pt
.. |to_lines| image:: images/qgis_icons/ftools/to_lines.png
              :width: 20pt
.. |sym_difference| image:: images/qgis_icons/ftools/sym_difference.png
                    :width: 20pt
.. |sum_points| image:: images/qgis_icons/ftools/sum_points.png
                :width: 20pt
.. |sum_lines| image:: images/qgis_icons/ftools/sum_lines.png
               :width: 20pt
.. |sub_selection| image:: images/qgis_icons/ftools/sub_selection.png
                   :width: 20pt
.. |split_layer| image:: images/qgis_icons/ftools/split_layer.png
                 :width: 20pt
.. |single_to_multi| image:: images/qgis_icons/ftools/single_to_multi.png
                     :width: 20pt
.. |simplify| image:: images/qgis_icons/ftools/simplify.png
              :width: 20pt
.. |select_location| image:: images/qgis_icons/ftools/select_location.png
                     :width: 20pt
.. |sampling| image:: images/qgis_icons/ftools/sampling.png
              :width: 20pt
.. |regular_points| image:: images/qgis_icons/ftools/regular_points.png
                    :width: 20pt
.. |random_selection| image:: images/qgis_icons/ftools/random_selection.png
                      :width: 20pt
.. |random_points| image:: images/qgis_icons/ftools/random_points.png
                   :width: 20pt
.. |neighbour| image:: images/qgis_icons/ftools/neighbour.png
               :width: 20pt
.. |multi_to_single| image:: images/qgis_icons/ftools/multi_to_single.png
                     :width: 20pt
.. |merge_shapes| image:: images/qgis_icons/ftools/merge_shapes.png
                  :width: 20pt
.. |mean| image:: images/qgis_icons/ftools/mean.png
          :width: 20pt
.. |matrix| image:: images/qgis_icons/ftools/matrix.png
            :width: 20pt
.. |management| image:: images/qgis_icons/ftools/management.png
                :width: 20pt
.. |layer_extent| image:: images/qgis_icons/ftools/layer_extent.png
                  :width: 20pt
.. |join_location| image:: images/qgis_icons/ftools/join_location.png
                   :width: 20pt
.. |join_attributes| image:: images/qgis_icons/ftools/join_attributes.png
                     :width: 20pt
.. |intersection| image:: images/qgis_icons/ftools/intersections.png
                  :width: 20pt
.. |intersect| image:: images/qgis_icons/ftools/intersect.png
               :width: 20pt
.. |help| image:: images/qgis_icons/ftools/help.png
          :width: 20pt
.. |geoprocessing| image:: images/qgis_icons/ftools/geoprocessing.png
                   :width: 20pt
.. |geometry| image:: images/qgis_icons/ftools/geometry.png
              :width: 20pt
.. |ftoolslogo2| image:: images/qgis_icons/ftools/ftoolslogo2.png
                 :width: 20pt
.. |ftools_logo| image:: images/qgis_icons/ftools/ftools_logo.png
                 :width: 20pt
.. |extract_nodes| image:: images/qgis_icons/ftools/extract_nodes.png
                   :width: 20pt
.. |export_projection| image:: images/qgis_icons/ftools/export_projection.png
                       :width: 20pt
.. |export_geometry| image:: images/qgis_icons/ftools/export_geometry.png
                     :width: 20pt
.. |dissolve| image:: images/qgis_icons/ftools/dissolve.png
              :width: 20pt
.. |difference| image:: images/qgis_icons/ftools/difference.png
                :width: 20pt
.. |delaunay| image:: images/qgis_icons/ftools/delaunay.png
              :width: 20pt
.. |define_projection| image:: images/qgis_icons/ftools/define_projection.png
                       :width: 20pt
.. |convex_hull| image:: images/qgis_icons/ftools/convex_hull.png
                 :width: 20pt
.. |clip| image:: images/qgis_icons/ftools/clip.png
          :width: 20pt
.. |check_geometry| image:: images/qgis_icons/ftools/check_geometry.png
                    :width: 20pt
.. |centroids| image:: images/qgis_icons/ftools/centroids.png
               :width: 20pt
.. |buffer| image:: images/qgis_icons/ftools/buffer.png
            :width: 20pt
.. |basic_statistics| image:: images/qgis_icons/ftools/basic_statistics.png
                      :width: 20pt
.. |analysis| image:: images/qgis_icons/ftools/analysis.png
              :width: 20pt
.. |gdal_contour| image:: images/qgis_icons/contour.png
                      :width: 20pt
.. |gdal_dem| image:: images/qgis_icons/gdal_dem.png
              :width: 20pt
.. |gdaledit| image:: images/qgis_icons/gdaledit.png
                    :width: 20 pt
.. |gdaltranslate| image:: images/qgis_icons/gdaltranslate.png
                    :width: 20 pt
.. |gdalwarp| image:: images/qgis_icons/gdalwarp.png
                    :width: 20 pt
.. |mActionSelect| image:: images/qgis_icons/mActionSelect.png
                    :width: 20 pt
.. |mActionCapturePoint| image:: images/qgis_icons/mActionCapturePoint.png
                         :width: 20 pt
"""

# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  Major themes that come with
# Sphinx are currently 'default' and 'sphinxdoc'.
html_theme = 'nature'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = 'ESSC'

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = 'ESSC FOSS-Geo'

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = 'images/logos.png'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
# html_favicon = 'favicon.ico'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
#html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
html_use_modindex = False

# If false, no index is generated.
html_use_index = False

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
html_use_opensearch = ''

# If nonempty, this is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = ''

# Output file base name for HTML help builder.
#htmlhelp_basename = 'sphinx_essc_geodoc'

# -- Options for LaTeX output --------------------------------------------------

# The paper size ('letter' or 'a4').
latex_paper_size = 'a4'

# The font size ('10pt', '11pt' or '12pt').
latex_font_size = '10pt'

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
   ('index', 'clp.tex', u'CLP-FFI-ESSC FOSS4G Workshop 2013',
   u' ', 'manual', 'False'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = 'images/logos.png'

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
latex_use_parts = False

# Additional stuff for the LaTeX preamble.

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_use_modindex = True

#If true, add page references after internal references. This is very useful for printed copies of the manual. Default is False.
## latex_show_pageref = True

#Control whether to display URL addresses. This is very useful for printed copies of the manual. The setting can have the following values:  'no' – do not display URLs (default); 'footnote' – display URLs in footnotes; 'inline' – display URLs inline in parentheses
latex_show_urls = True

latex_elements = {
     'classoptions': 
     ',openany,oneside', 
     'babel' : '\\usepackage[english]{babel}'
    }


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'http://docs.python.org/': None}

#edit checks
todo_include_todos = True
